### ISSUE TITLE
Add opportunity to add fetch options

### ISSUE THREAD

**Issue by jmas** [salikovpro/fetch-to-request#2]
For now we can't change `fetch()` options.
Case when we need that: switch on `credentials: 'include'` to enable send browser cookies. Also sometimes we need to enable other options.
Currently fetch-to-request is static class, but it will be better if I can init fetch-to-request with default options that will be applied to fetch automatically.
Example:
```
const http = new FetchToRequest({
    credentials: 'include',
});
http.get(url, specificOptions); // automatically will be called with default options.
http.post(url, data, specificOptions); // also it will be great to pass specific options here.
```
Thanks for lib. Good luck.

**Comment by salikovpro** [comment]
Resolved with https://github.com/salikovpro/fetch-to-request/commit/4ab945a9748a6e3602ac2cfffbecf7bf90550933

**Comment by jmas** [comment]
@salikovpro 👍 thanks!
